version: "3"
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    restart: always
    ports:
      - "8080:8080"
    command: ["sh", "-c", "cd /src && air"]
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - POSTGRES_ADDR=5432
      - POSTGRES_HOST=postgres
      - PORT=8080
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    tty: true
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
