version: '3'
services:
  my-golang-app:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    depends_on:
      - db
  db:
    build: 
      context: .
      dockerfile: ./db/Dockerfile
    tty: true
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
